// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzwkggtejlviflmcnyfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6d2tnZ3Rlamx2aWZsbWNueWZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTI5MjUsImV4cCI6MjA3MDMyODkyNX0.CHyLuJpsT2USFHP1nkmZkN2R5yuxHd3kL1dbhwjr_VA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});